backend:
  name: git-gateway
  branch: master
media_folder: "static/images"
collections:
  - name: "Home Page" 
    label: "Home Page"
    folder: "content/english"
    create: false
    fields:
      - { label: "Home Title", name: "title", widget: "string" }
      - { label: "Services Title", name: "services_title", widget: "string" }
      - { label: "Business Title", name: "business_title", widget: "string" }
      - { label: "Business Subtitle", name: "business_subtitle", widget: "string" }
      - { label: "Business Content", name: "business_content", widget: "text" }
      - { label: "About Image URL", name: "adout_image_url", widget: "image" }
      - { label: "About Title", name: "about_title", widget: "string" }
      - { label: "About Subtitle", name: "about_subtitle", widget: "string" }
      - { label: "About Content 1", name: "about_content1", widget: "text" }
      - { label: "About Content 2", name: "about_content2", widget: "text" }
      - { label: "Testimonial Title", name: "testimonial_title", widget: "string" }
      - { label: "Testimonial Subtitle", name: "testimonial_subtitle", widget: "string" }
      

  - name: "About Section" 
    label: "About Section"
    folder: "content/english/about"
    create: false
    fields:
      - { label: "Main Title", name: "title", widget: "string" }
      - { label: "About Subtitle", name: "sub_title", widget: "string" }
      - { label: "About Image", name: "page_header_bg", widget: "image" }
      - { label: "About Meta Description", name: "description", widget: "text" }
      - { label: "About Title", name: "about_title", widget: "string" }
      - { label: "About Subtitle", name: "about_subtitle", widget: "string" }
      - { label: "About Content1", name: "about_content1", widget: "text" }
      - { label: "About Content2", name: "about_content2", widget: "text" }
      - { label: "About Background Image ", name: "about_bg_image_url", widget: "image" }

  - name: "Contact Section" 
    label: "Contact"
    folder: "content/english/contact"
    create: false
    fields:
      - { label: "Contact Title", name: "title", widget: "string" }
      - { label: "Contact Subtitle", name: "sub_title", widget: "string" }
      - { label: "Contact Image", name: "page_header_bg", widget: "image" }
      - { label: "Contact Meta Description", name: "description", widget: "text" }
      - { label: "Contact No", name: "phone", widget: "string" }
      - { label: "Contact Email", name: "email", widget: "string" }
      - { label: "Contact Address", name: "location", widget: "string" }
      
  - name: "Business Section" 
    label: "Business-section"
    folder: "content/english/home/business-section"
    create: true
    fields:
      - { label: "Business Title", name: "title", widget: "string" }
      - { label: "Business Count", name: "count", widget: "string" }
      - { label: "Business Type", name: "type", widget: "string" }
   
  - name: "Client Section" 
    label: "Client-Section"
    folder: "content/english/home/client-section"
    create: true
    fields:
      - { label: "Client Title", name: "title", widget: "string" }
      - { label: "Client Image", name: "client_image_url", widget: "image" }
      - { label: "Client Type", name: "type", widget: "string" }
   
  - name: "Financial Services" 
    label: "Financial-Services"
    folder: "content/english/home/financial-services"
    create: true
    fields:
      - { label: "Service Title", name: "title", widget: "string" }
      - { label: "Service Image URL", name: "service_image_url", widget: "image" }
      - { label: "Service Content", name: "service_content", widget: "text" }
      - { label: "Service Type", name: "type", widget: "string" }

  - name: "Banner Section" 
    label: "Banner"
    folder: "content/english/home/banner-section"
    create: true
    fields:
      - { label: "Banner Title", name: "title", widget: "string" }
      - { label: "Banner Heading", name: "banner_heading", widget: "string" }
      - { label: "Banner Content", name: "banner_content", widget: "text" }
      - { label: "Banner Type", name: "type", widget: "string" }
   
  - name: "Testimonial Section" 
    label: "Testimonial"
    folder: "content/english/home/testimonials"
    create: true
    fields:
      - { label: "Testimonial Title", name: "title", widget: "string" }
      - { label: "Testimonial Designation", name: "testimonial_designation", widget: "string" }
      - { label: "Testimonial Content", name: "testimonial_content", widget: "text" }
      - { label: "Testimonial Type", name: "type", widget: "string" }
    
    
  - name: "Our Service" 
    label: "Our-Service"
    folder: "content/english/our-services"
    create: true
    fields:
      - { label: "Service Name", name: "title", widget: "string" }
      - { label: "Service Image URL", name: "service_image_url", widget: "image" }
      - { label: "Service Content", name: "service_content", widget: "text" }
      - { label: "Type", name: "type", widget: "string" }